[package]
name = "pythonic-helper"
version = "0.1.0"
edition = "2021"
description = "A library that provides Python-like functions (and some surprises)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
