name: Test and Publish

on:
  push:
    paths:
      - "**.rs"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
      - "Cargo.toml"
  pull_request:
    paths:
      - "**.rs"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
      - "Cargo.toml"
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Upgrade Rust tools
        run: rustup update
      
      - name: Test
        run: cargo test
      
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}