name: Test and Publish

on:
  push:
    paths:
      - "**.rs"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
      - "Cargo.toml"
  pull_request_target:
    paths:
      - "**.rs"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
      - "Cargo.toml"
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Upgrade Rust tools
        run: rustup update
      
      - name: Build
        run: cargo build
      
      - name: Clippy
        run: cargo clippy
      
      - name: Test
        run: cargo test
      
      - name: Publish
        # Run only when a new file is added, modified, or the Cargo.toml file is modified. (And the target is the `main` branch)
        if: (contains(github.event.commits[0].added, 'src/') || contains(github.event.commits[0].modified, 'src/') || contains(github.event.commits[0].modified, 'Cargo.toml')) && (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.head.ref == 'main' && github.pull_request.merged == true)
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}